# Generated by Django 4.0.5 on 2023-03-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_app', '0002_alter_rating_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
